// <auto-generated />
namespace Clientes2S_Backend_Auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addUserColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUserColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201609072054081_addUserColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
