// <auto-generated />
namespace Clientes2S_Backend_Auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_userId_To_Contact_and_Job : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_userId_To_Contact_and_Job));
        
        string IMigrationMetadata.Id
        {
            get { return "201609091603490_Add_userId_To_Contact_and_Job"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
